/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import Utils.ShareHelper;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;
import qlthuoc.BanThuoc;
import qlthuoc.ChaoJDialog;
import qlthuoc.DangNhapJDialog;
import qlthuoc.ListHoaDon;
import qlthuoc.LoaiDuocPhamJDialog;
import qlthuoc.NhaCungCapJDialog;
import qlthuoc.QuanLyNhanVien;
import qlthuoc.ThongKe;
import qlthuoc.ThongTinNhanVienJDialog;
import qlthuoc.ThuocJDiagram;

/**
 *
 * @author nguye
 */
public class MainThuocJFrame extends javax.swing.JFrame {
    private MP3 mp3;
    private boolean check = false;

    /**
     * Creates new form MainThuocJFrame
     */
    public MainThuocJFrame() {
        initComponents();
        mp3 = new MP3("src//Sound//Vitas.mp3");
//        mp3.play();
        init();
        check = true;
        Image us = Toolkit.getDefaultToolkit().createImage("src\\Icons\\logocuabeHung.png");
        this.setIconImage(us);
    }

    public void init() {
        setLocationRelativeTo(null);
        setTitle("Quản lý nhà thuốc Long Phụng Sum Vầy");
        if (check) {
            new DangNhapJDialog(this, true).setVisible(true);
        } else {
            new ChaoJDialog(this, true).setVisible(true);
            new DangNhapJDialog(this, true).setVisible(true);
        }
        
        mp3.stop();

        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblDongHo2.setText(format.format(new Date()));
                lblDongHo3.setText(format.format(new Date()));
                lblDongHo4.setText(format.format(new Date()));
            }
        }).start();

        if (!ShareHelper.isManager()) {
            tpMenu.setEnabledAt(0, false);
            tpMenu.setEnabledAt(1, true);
            tpMenu.setSelectedIndex(1);
        } else {
            tpMenu.setEnabledAt(1, false);
            tpMenu.setEnabledAt(0, true);
            tpMenu.setSelectedIndex(0);
        }
        lblTrangThai1.setText(ShareHelper.USER.getTen());
        lblTrangThai2.setText(ShareHelper.USER.getTen());
        lblTrangThai1.setText(ShareHelper.USER.getTen());
        
        
    }

    public void dangXuat() {
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất không ?",
                "Hệ thống quản lý nhà thuốc: Long Phụng Sum Vầy", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            ShareHelper.logoff();
            init();
        }
    }
    
    class MP3 {
        private Player player;
        private String filename;

        public MP3(String filename) {
            this.filename = filename;
        }

        public void stop() {
            if (player != null) {
                player.close();
            }
        }

        public void play() {
            try {
                BufferedInputStream bis = new BufferedInputStream(new FileInputStream(filename));
                player = new Player(bis);
            } catch (FileNotFoundException | JavaLayerException ex) {
                System.out.println(ex);
            }
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        player.play();
                    } catch (Exception ex) {
                        System.out.println(ex);
                    }
                }
            }).start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        tpMenu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jtb1 = new javax.swing.JToolBar();
        btnNhanVien = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnNhaCungCap = new javax.swing.JButton();
        btnLoaiThuoc = new javax.swing.JButton();
        btnThuoc = new javax.swing.JButton();
        btnNhapThuoc = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnThongKe = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnDangXuatQL = new javax.swing.JButton();
        pnlTrangThai1 = new javax.swing.JPanel();
        lblDongHo2 = new javax.swing.JLabel();
        lblTrangThai1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtb2 = new javax.swing.JToolBar();
        btnBanThuoc = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        btnListHD = new javax.swing.JButton();
        btnThongTinThuoc = new javax.swing.JButton();
        btnTaiKhoan = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnDangXuatBH = new javax.swing.JButton();
        pnlTrangThai2 = new javax.swing.JPanel();
        lblDongHo3 = new javax.swing.JLabel();
        lblTrangThai2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pnlTrangThai3 = new javax.swing.JPanel();
        lblDongHo4 = new javax.swing.JLabel();
        lblTrangThai3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpMenu.setForeground(new java.awt.Color(14, 144, 238));
        tpMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jtb1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtb1.setRollover(true);

        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User.png"))); // NOI18N
        btnNhanVien.setText(" Nhân viên ");
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        jtb1.add(btnNhanVien);
        jtb1.add(jSeparator1);

        btnNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User group.png"))); // NOI18N
        btnNhaCungCap.setText("Nhà cung cấp");
        btnNhaCungCap.setFocusable(false);
        btnNhaCungCap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhaCungCap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaCungCapActionPerformed(evt);
            }
        });
        jtb1.add(btnNhaCungCap);

        btnLoaiThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Label.png"))); // NOI18N
        btnLoaiThuoc.setText(" Loại thuốc ");
        btnLoaiThuoc.setFocusable(false);
        btnLoaiThuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLoaiThuoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLoaiThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiThuocActionPerformed(evt);
            }
        });
        jtb1.add(btnLoaiThuoc);

        btnThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bottle_of_pills-removebg-preview.png"))); // NOI18N
        btnThuoc.setText("   Thuốc   ");
        btnThuoc.setFocusable(false);
        btnThuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThuoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuocActionPerformed(evt);
            }
        });
        jtb1.add(btnThuoc);

        btnNhapThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add to basket.png"))); // NOI18N
        btnNhapThuoc.setText("Nhập thuốc");
        btnNhapThuoc.setFocusable(false);
        btnNhapThuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhapThuoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhapThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapThuocActionPerformed(evt);
            }
        });
        jtb1.add(btnNhapThuoc);
        jtb1.add(jSeparator6);
        jtb1.add(jSeparator4);

        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Bar chart.png"))); // NOI18N
        btnThongKe.setText(" Thống kê ");
        btnThongKe.setFocusable(false);
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        jtb1.add(btnThongKe);
        jtb1.add(jSeparator3);

        btnDangXuatQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Exit.png"))); // NOI18N
        btnDangXuatQL.setText("Đăng xuất");
        btnDangXuatQL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuatQL.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuatQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatQLActionPerformed(evt);
            }
        });
        jtb1.add(btnDangXuatQL);

        pnlTrangThai1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDongHo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Clock.png"))); // NOI18N
        lblDongHo2.setText("09:07:47 AM");

        lblTrangThai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User.png"))); // NOI18N
        lblTrangThai1.setText("Tên nhân viên");

        javax.swing.GroupLayout pnlTrangThai1Layout = new javax.swing.GroupLayout(pnlTrangThai1);
        pnlTrangThai1.setLayout(pnlTrangThai1Layout);
        pnlTrangThai1Layout.setHorizontalGroup(
            pnlTrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrangThai1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrangThai1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo2)
                .addContainerGap())
        );
        pnlTrangThai1Layout.setVerticalGroup(
            pnlTrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangThai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblDongHo2)
                .addComponent(lblTrangThai1))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logoThuoc.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtb1, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTrangThai1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jtb1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlTrangThai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tpMenu.addTab("Quản lý", jPanel1);

        jtb2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtb2.setRollover(true);

        btnBanThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Cash register.png"))); // NOI18N
        btnBanThuoc.setText(" Bán thuốc ");
        btnBanThuoc.setFocusable(false);
        btnBanThuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBanThuoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBanThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanThuocActionPerformed(evt);
            }
        });
        jtb2.add(btnBanThuoc);
        jtb2.add(jSeparator9);

        btnListHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lists.png"))); // NOI18N
        btnListHD.setText("Hóa đơn");
        btnListHD.setFocusable(false);
        btnListHD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListHD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnListHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListHDActionPerformed(evt);
            }
        });
        jtb2.add(btnListHD);

        btnThongTinThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Info.png"))); // NOI18N
        btnThongTinThuoc.setText("Thông tin thuốc");
        btnThongTinThuoc.setFocusable(false);
        btnThongTinThuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongTinThuoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongTinThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinThuocActionPerformed(evt);
            }
        });
        jtb2.add(btnThongTinThuoc);

        btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User.png"))); // NOI18N
        btnTaiKhoan.setText(" Tài khoản ");
        btnTaiKhoan.setFocusable(false);
        btnTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTaiKhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });
        jtb2.add(btnTaiKhoan);
        jtb2.add(jSeparator7);

        btnDangXuatBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Exit.png"))); // NOI18N
        btnDangXuatBH.setText(" Đăng xuất ");
        btnDangXuatBH.setFocusable(false);
        btnDangXuatBH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuatBH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuatBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatBHActionPerformed(evt);
            }
        });
        jtb2.add(btnDangXuatBH);

        pnlTrangThai2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDongHo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Clock.png"))); // NOI18N
        lblDongHo3.setText("09:07:47 AM");

        lblTrangThai2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User.png"))); // NOI18N
        lblTrangThai2.setText("Tên nhân viên");

        javax.swing.GroupLayout pnlTrangThai2Layout = new javax.swing.GroupLayout(pnlTrangThai2);
        pnlTrangThai2.setLayout(pnlTrangThai2Layout);
        pnlTrangThai2Layout.setHorizontalGroup(
            pnlTrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrangThai2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrangThai2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo3)
                .addContainerGap())
        );
        pnlTrangThai2Layout.setVerticalGroup(
            pnlTrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangThai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblDongHo3)
                .addComponent(lblTrangThai2))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logoThuoc.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel4)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtb2, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
            .addComponent(pnlTrangThai2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jtb2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlTrangThai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tpMenu.addTab("Bán hàng", jPanel2);

        pnlTrangThai3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDongHo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Clock.png"))); // NOI18N
        lblDongHo4.setText("09:07:47 AM");

        lblTrangThai3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User.png"))); // NOI18N
        lblTrangThai3.setText("Tên nhân viên");

        javax.swing.GroupLayout pnlTrangThai3Layout = new javax.swing.GroupLayout(pnlTrangThai3);
        pnlTrangThai3.setLayout(pnlTrangThai3Layout);
        pnlTrangThai3Layout.setHorizontalGroup(
            pnlTrangThai3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrangThai3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrangThai3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo4)
                .addContainerGap())
        );
        pnlTrangThai3Layout.setVerticalGroup(
            pnlTrangThai3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangThai3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblDongHo4)
                .addComponent(lblTrangThai3))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTrangThai3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 481, Short.MAX_VALUE)
                .addComponent(pnlTrangThai3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tpMenu.addTab("Thông tin liên hệ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
//        new XemTTNhanVienJFrame().setVisible(true);
        new QuanLyNhanVien().setVisible(true);
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnBanThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanThuocActionPerformed
        new BanThuoc().setVisible(true);
    }//GEN-LAST:event_btnBanThuocActionPerformed

    private void btnNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaCungCapActionPerformed
        new NhaCungCapJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnNhaCungCapActionPerformed

    private void btnLoaiThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiThuocActionPerformed
        new LoaiDuocPhamJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnLoaiThuocActionPerformed

    private void btnThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuocActionPerformed
        new ThuocJDiagram(this, true).setVisible(true);
    }//GEN-LAST:event_btnThuocActionPerformed

    private void btnNhapThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapThuocActionPerformed

    }//GEN-LAST:event_btnNhapThuocActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        new ThongKe(this, true).setVisible(true);
    }//GEN-LAST:event_btnThongKeActionPerformed
    public static ThuocJDiagram t;
    private void btnThongTinThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinThuocActionPerformed
        new ThuocJDiagram(this, true).setVisible(true);
    }//GEN-LAST:event_btnThongTinThuocActionPerformed

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        new ThongTinNhanVienJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnDangXuatBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatBHActionPerformed
        dangXuat();
    }//GEN-LAST:event_btnDangXuatBHActionPerformed

    private void btnDangXuatQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatQLActionPerformed
        dangXuat();
    }//GEN-LAST:event_btnDangXuatQLActionPerformed

    private void btnListHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListHDActionPerformed
        new ListHoaDon(this, true).setVisible(true);
    }//GEN-LAST:event_btnListHDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainThuocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainThuocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainThuocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainThuocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainThuocJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanThuoc;
    private javax.swing.JButton btnDangXuatBH;
    private javax.swing.JButton btnDangXuatQL;
    private javax.swing.JButton btnListHD;
    private javax.swing.JButton btnLoaiThuoc;
    private javax.swing.JButton btnNhaCungCap;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnNhapThuoc;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnThongTinThuoc;
    private javax.swing.JButton btnThuoc;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jtb1;
    private javax.swing.JToolBar jtb2;
    private javax.swing.JLabel lblDongHo2;
    private javax.swing.JLabel lblDongHo3;
    private javax.swing.JLabel lblDongHo4;
    private javax.swing.JLabel lblTrangThai1;
    private javax.swing.JLabel lblTrangThai2;
    private javax.swing.JLabel lblTrangThai3;
    private javax.swing.JPanel pnlTrangThai1;
    private javax.swing.JPanel pnlTrangThai2;
    private javax.swing.JPanel pnlTrangThai3;
    private javax.swing.JTabbedPane tpMenu;
    // End of variables declaration//GEN-END:variables
}
